# Generated by Django 5.1.3 on 2025-03-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_aboutus_category_img_offer_order_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(default='example', upload_to='profile_image'),
            preserve_default=False,
        ),
    ]
